version: "3.8"
services:
  web:
    image: 026090538055.dkr.ecr.ap-south-1.amazonaws.com/sampleapp/frontend:latest
    ports:
      - "3000:3000"
    networks:
      - network-backend

  api:
    image: 026090538055.dkr.ecr.ap-south-1.amazonaws.com/sampleapp/backend:latest
    ports:
      - "3001:3001"
    networks:
      - network-backend

networks:
  network-backend:
