version: '3.8'

services:
  backend:
    image: 026090538055.dkr.ecr.ap-south-1.amazonaws.com/sampleapp/backend:latest
    ports:
      - "5000:5000"  # Map backend port
    environment:
      - ENV_VAR_NAME=value  # Add any necessary environment variables

  frontend:
    image: 026090538055.dkr.ecr.ap-south-1.amazonaws.com/sampleapp/frontend:latest
    ports:
      - "3000:3000"  # Map frontend port
    environment:
      - ENV_VAR_NAME=value  # Add any necessary environment variables
